import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

const messages = {
  en: { home:'Home',about:'About',projects:'Projects',achievements:'Achievements',contact:'Contact',navigation:'Navigation',hello:'Say hello',backTop:'Back to top',skip:'Skip to content',freelance:'Available for freelance projects',heroStart:'I create digital experiences that feel',heroAccent:'fast, clear,',heroEnd:'and memorable.',heroText:'I’m Adham, a frontend developer and student from Uzbekistan. I turn thoughtful ideas into responsive interfaces built for real people.',viewWork:'View my work',letsTalk:'Let’s talk',projectsBuilt:'Projects built',toolsExplored:'Tools explored',yearsLearning:'Years of learning',learningStreak:'Day learning streak',footerText:'I design and build useful frontend experiences with care, curiosity, and a good cup of tea.',footerLegal:'Built with React and curiosity.',availableWork:'Available for thoughtful freelance work.',language:'Language',projectMind:'Have a project in mind?',makeSomething:'Let’s make something',worthUsing:'worth using.',ctaText:'I’m open to thoughtful collaborations, frontend work, and a good conversation about a useful idea.',startConversation:'Start a conversation',copyEmail:'Copy email',newWork:'Available for new work' },
  uz: { home:'Bosh sahifa',about:'Men haqimda',projects:'Loyihalar',achievements:'Yutuqlar',contact:'Aloqa',navigation:'Navigatsiya',hello:'Bog‘lanish',backTop:'Yuqoriga',skip:'Asosiy qismga o‘tish',freelance:'Frilans loyihalar uchun ochiqman',heroStart:'Men',heroAccent:'tez, tushunarli',heroEnd:'va esda qolarli raqamli tajribalar yarataman.',heroText:'Men Adham — O‘zbekistondan frontend dasturchi va talabaman. Puxta g‘oyalarni haqiqiy insonlar uchun moslashuvchan interfeyslarga aylantiraman.',viewWork:'Ishlarimni ko‘rish',letsTalk:'Suhbatlashamiz',projectsBuilt:'Yaratilgan loyihalar',toolsExplored:'O‘rganilgan vositalar',yearsLearning:'Yillik tajriba',learningStreak:'Kunlik o‘rganish seriyasi',footerText:'Men e’tibor, qiziqish va bir piyola yaxshi choy bilan foydali frontend tajribalarini yarataman.',footerLegal:'React va qiziqish bilan yaratildi.',availableWork:'Puxta frilans ishlari uchun ochiqman.',language:'Til',projectMind:'Loyihangiz bormi?',makeSomething:'Keling,',worthUsing:'foydalanishga arziydigan narsa yaratamiz.',ctaText:'Mazmunli hamkorlik, frontend ishlari va foydali g‘oya haqidagi yaxshi suhbatga tayyorman.',startConversation:'Suhbatni boshlash',copyEmail:'Emailni nusxalash',newWork:'Yangi ishlar uchun ochiqman' },
  ru: { home:'Главная',about:'Обо мне',projects:'Проекты',achievements:'Достижения',contact:'Контакты',navigation:'Навигация',hello:'Связаться',backTop:'Наверх',skip:'Перейти к содержанию',freelance:'Открыт для фриланс-проектов',heroStart:'Я создаю цифровые продукты —',heroAccent:'быстрые, понятные',heroEnd:'и запоминающиеся.',heroText:'Я Адхам, frontend-разработчик и студент из Узбекистана. Превращаю продуманные идеи в адаптивные интерфейсы для реальных людей.',viewWork:'Посмотреть работы',letsTalk:'Обсудить проект',projectsBuilt:'Готовых проектов',toolsExplored:'Изученных инструментов',yearsLearning:'Года обучения',learningStreak:'Дней без перерыва',footerText:'Я внимательно и с интересом создаю полезные frontend-продукты — и не забываю о чашке хорошего чая.',footerLegal:'Создано с React и любопытством.',availableWork:'Открыт для интересных фриланс-задач.',language:'Язык',projectMind:'Есть идея проекта?',makeSomething:'Давайте создадим то, чем',worthUsing:'действительно хочется пользоваться.',ctaText:'Я открыт для продуманных совместных проектов, frontend-разработки и хорошего разговора о полезной идее.',startConversation:'Начать разговор',copyEmail:'Скопировать email',newWork:'Открыт для новых проектов' },
}

const LanguageContext = createContext(null)
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('adham-language') || 'uz')
  useEffect(() => { localStorage.setItem('adham-language', language); document.documentElement.lang = language }, [language])
  const value = useMemo(() => ({ language, setLanguage, t: (key) => messages[language]?.[key] ?? messages.en[key] ?? key }), [language])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
export function useLanguage() { const value = useContext(LanguageContext); if (!value) throw new Error('useLanguage must be used inside LanguageProvider'); return value }
